name: Deploy jB-Superset

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build Docker Image and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker buildx build \
            -t ${{ secrets.DOCKER_REGISTRY }}/superset:${{ github.sha }} \
            --target dev \
            --cache-from=type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/superset-cache:latest \
            .

      - name: Run Tests
        run: |
          docker run --rm ${{ secrets.DOCKER_REGISTRY }}/superset:${{ github.sha }} bash -c "npm run test"

      - name: Run Lint
        run: |
          docker run --rm ${{ secrets.DOCKER_REGISTRY }}/superset:${{ github.sha }} bash -c "npm run eslint -- . --quiet"

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/superset:${{ github.sha }}

  deploy:
    name: Deploy jB-Superset Image
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Create .env-local File on Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/jB-superset/docker
            cat << 'EOF' > .env-local
            ${{ secrets.ENV_LOCAL }}
            EOF

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/jB-superset
            echo "SUPERSET_IMAGE=${{ secrets.DOCKER_REGISTRY }}/superset:${{ github.sha }}" > .env
            docker-compose pull
            docker-compose up -d --no-build