name: Deploy jB-Superset

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Superset Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./superset-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '^18.19.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-assets
          path: superset/static/assets/

  build-and-push-docker:
    name: Build Docker Image and Run Tests
    needs: build-frontend
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-assets
          path: ./superset/static/assets/

      - name: Verify artifact contents
        run: ls -R ./superset/static/assets

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        id: build-image
        env:
          ECR_REGISTRY: ${{ vars.AWS_ECR_REGISTRY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build \
          --file no-frontend.Dockerfile \
          --tag $ECR_REGISTRY:$IMAGE_TAG \
          --push \
          .
           echo "image=$ECR_REGISTRY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy-to-ec2:
    name: Deploy Docker Image to Server
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Create .env File on Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/jB-superset
            cat << 'EOF' > .env
            ${{ secrets.ENV }}
            EOF

      - name: Deploy to Server
        env:
          IMAGE_NAME: ${{ steps.build-and-push-docker.outputs.image }}
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/jB-superset
            echo "SUPERSET_IMAGE=$IMAGE_NAME" > .env
            docker-compose pull
            docker-compose -f docker-compose-prod.yml up -d --no-build